README.md, auth_jwt.go, auth_jwt_test.go, example/server.go
I think it may be useful / convenient to be aware of the request context to authenticate or to be able to interact with it so that Authorizator can have access to variables set previously in Authenticator.
=> added Gin Context to authenticator

auth_jwt.go, auth_jwt_test.go
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
Fixed #36
=> errors should always be lower case

auth_jwt.go, auth_jwt_test.go
fix #63 
cc @dhdresser @djensen47
=> fix: move the check for Authenticator to login handler.

auth_jwt.go, auth_jwt_test.go
Error can be used to validate method response. Also we need to have expiration date here to send with token to end-user.
=> Update token generator to return expiration date and error

auth_jwt.go, auth_jwt_test.go
fix https://github.com/appleboy/gin-jwt/issues/106
set custom refresh response: 
```go
authMiddleware := &GinJWTMiddleware{
Realm:            "test zone",
Key:              key,
Timeout:          time.Hour,
MaxRefresh:       time.Hour * 24,
SigningAlgorithm: "RS256",
PrivKeyFile:      "testdata/jwtRS256.key",
PubKeyFile:       "testdata/jwtRS256.key.pub",
Authenticator: func(userId string, password string, c *gin.Context) (interface{}, bool) {
if userId == "admin" && password == "admin" {
return userId, true
}
return userId, false
},
RefreshResponse: func(c *gin.Context, code int, token string, t time.Time) {
c.JSON(http.StatusOK, gin.H{
"code":    http.StatusOK,
"token":   token,
"expire":  t.Format(time.RFC3339),
"message": "refresh successfully",
})
},
}
```
=> feat: support custom login or refresh response

auth_jwt.go
Hi.  
I want to use TokenGenerator func like below but there is a simple issue.
```
func TestAuthMiddleWare(t *testing.T) {
authMiddleware := &jwt.GinJWTMiddleware{
Realm: "test Zone",
Key: []byte("secret key"),
Timeout: time.Hour,
MaxRefresh: time.Hour,
Authenticator: Authenticator,
Authorizator: Authorizator,
Unauthorized: Unauthorized,
PayloadFunc: PayloadFunc,
TokenLookup: "header:Authorization",
TokenHeadName: "Bearer",
TimeFunc: time.Now,
}
authMiddleware.MiddlewareInit()
// ** cannot use User literal (type *User) as type MapClaims **
token, _, _ := authMiddleware.TokenGenerator("admin", &User{
UserName: "admin",
LastName: "Bo-Yi",
FirstName: "Wu",
})
}
func PayloadFunc(data interface{}) jwt.MapClaims {
user := data.(*User)
return jwt.MapClaims{
"UserName": user.UserName, …
```
=> Update TokenGenerator data from MapClaims to interface

auth_jwt.go, auth_jwt_test.go
fix https://github.com/appleboy/gin-jwt/issues/152
fix https://github.com/appleboy/gin-jwt/pull/155
=> refactor: add identity as key name.

README.md, auth_jwt.go, example/basic/server.go
fix https://github.com/appleboy/gin-jwt/issues/158
=> fix: IdentityHandler arg

auth_jwt.go
1) added a nil check in refreshHandler to prevent panic when token is nil, this is when there is no JWT in cookie
2) refactored code to new RefreshToken func, for ppl who like to refresh everytime in Authorization or every request
3) refactored code to new CheckIfTokenExpire func, for ppl who like to only check if token is expired in Authorization, mainly for SPA use, one way to refresh is to only refresh on application load
=> nil check in refreshHandler + refreshHandler code refactoring

README.md, auth_jwt.go, auth_jwt_test.go, example/basic/server.go
=> feat: parse jwt token in url path.

auth_jwt.go, auth_jwt_test.go
=> custom cookie name

.drone.yml, Makefile, go.mod, go.sum, vendor/vendor.json
See https://github.com/golang/go/issues/26794#issuecomment-428631725
=> feat: install go module first before run go test

auth_jwt.go, auth_jwt_test.go
=> fix: Prevent panic when exp claim is empty or a string

README.md, auth_jwt.go, auth_jwt_test.go, go.sum
Adds a basic `LogoutHandler` (with customizable `LogoutResponse` object like `LoginResponse`) to the middleware allowing users to add a route to have the jwt cookie deleted using the same settings as were used to create the cookie.
=> Add LogoutHandler and LogoutResponse to allow user to remove jwt cookie

auth_jwt.go
implements a feature that allows to choose how long the cookie will be valid, and also using mw.Timeout value for a cookie isn't right, since it's just not possible to refresh a jwt if maxAge of cookie is the same as jwt timeout value if the user has chosen to store jwt in cookies
If you don't want to implement that feature I'd ask you to update maxAge value in cookie to be
`expireCookie := mw.TimeFunc().Add(mw.CookieMaxAge)`
`maxage := int(expireCookie.Unix() - time.Now().Unix())`
and not 
`expire := mw.TimeFunc().Add(mw.Timeout)`
so user would be at least able to refresh a token if it's stored in cookies.
=> implements CookieMaxAge value

auth_jwt.go, auth_jwt_test.go
fixes https://github.com/appleboy/gin-jwt/issues/248
=> calculate cookie max-age using TimeFunc

README.md, _example/basic/server.go
This PR should resolve #255 
after defind authMiddleware ,developer need call MiddlewareInit by themself  
we should add this code into  ```Example```
```go
errInit := authMiddleware.MiddlewareInit()
if errInit != nil {
log.Fatal("authMiddleware.MiddlewareInit() Error:" + errInit.Error())
}
```
=> developer need call MiddlewareInit by themself 

auth_jwt.go, auth_jwt_test.go
This pull request allows us to add public and private key's using ```[]byte``` rather than file path
1. In serverless environments, file system access is not always available.
2. Will allow support for hosted secrets storage, i.e Google Secrets Manager, Azure Key Vault
3. Resolves a [query](https://github.com/appleboy/gin-jwt/pull/80#issuecomment-353788381) from the original pull request
We decided to extend the API to maintain backward compatibility and we give file path option priority over ```[]byte``` option.
=> Allow asymmetric key in []byte

README.md
CookieSameSite exists, but it was not mentioned in README.md.
=> Add CookieSameSite to README.md

auth_jwt.go
As mentioned in [Issue 292](https://github.com/appleboy/gin-jwt/issues/292), we all participated in the training camp organized by ByteDance. They recommended this lightweight middleware for our project. The job assigned to us needs to parse the token from the POST form data, which have not been supported by this middleware. So I wish to add a parsing option to support this and it works fine in my own project.
=> Add an option to parse token from POST form data.

auth_jwt.go, auth_jwt_test.go
fix https://github.com/appleboy/gin-jwt/pull/287
Signed-off-by: Bo-Yi.Wu <appleboy.tw@gmail.com>
=> feat(jwt): adds ParseOption to Parse method of jwt

_example/basic/server.go, auth_jwt.go, auth_jwt_test.go
The current implementation doesn't handle `jwt.WithJSONNumber()` parse option well, if you set this option and try to parse a JWT, it always fails type conversion here:
https://github.com/appleboy/gin-jwt/blob/6b68cb3e1879fc8f8936ee7a7cbb65e40e389e66/auth_jwt.go#L430-L433
We should also take care of the type `json.Number` and avoid the false alarm, this is also what https://github.com/golang-jwt/jwt/blob/main/map_claims.go#L40-L56 does.
=> bug: fix the false alarm of verification with jwt.WithJSONNumber

auth_jwt.go
Only in `TokenGenerator` `mw.TimeFunc().UTC()` is called (all other places do not call `UTC`), making the result inconsistent with the result of other functions.
=> fix(timezone): remove stray `UTC()` call

auth_jwt.go, auth_jwt_test.go
1. **DRY Code:** The `SetCookie` code is redundant we’ve duplicated the logic for setting cookies in both the `LoginHandler` and `RefreshToken`.
2. We do have the `func (*GinJWTMiddleware) TokenGenerator` method for clients to generate `JWT` tokens independently of the `LoginHandler` or `RefreshToken` methods. However, without a dedicated `SetCookie` method, cookie setting remains tightly coupled with these methods. Introducing a `SetCookie` method would enhance scalability by enabling cookies to be set independently, eliminating the need for manual cookie handling where such functionality is currently absent.
**Context:** 
This library looks very useful for us. However at the moment I don't think it supports `oauth`? Basically I don't want my users to register with a username/password, …
=> refactor: Provided an Option to Set Cookie using *GinJWTMiddleware

_example/basic/server.go
Server Example has a typo that causes an error.
=> Remove typo server.go

auth_jwt.go
=> feat: set timeout dynamically - Add TimeoutFunc

auth_jwt.go
My old token didn't use 'exp' as expire field, so I need a custom exp field.
Tested by your unit test.
=> feat: add custom ExpField

auth_jwt.go, auth_jwt_test.go
- Remove the custom `MapClaims` type definition
- Replace `MapClaims` with `jwt.MapClaims` in `PayloadFunc`, `GetClaimsFromJWT`, `ExtractClaims`, and `ExtractClaimsFromToken` functions
- Update test cases to use `jwt.MapClaims` instead of the custom `MapClaims`
- Update `ConvertClaims` function to accept `jwt.MapClaims`
fix #341
=> refactor: adopt jwt.MapClaims to replace custom MapClaims type

auth_jwt.go, auth_jwt_test.go
This pull request updates the `MapClaims` struct to be an alias of the golang-jwt library's MapClaims instead of requiring all the downstream functions to use the `golang-jwt` library's struct. 
This helps a lot with breaking changes (such as the one introduced in the last tag) because it means that the function inputs can be consistent, and it prevents anyone who uses `MapClaims` in upstream code from needing to import `golang-jwt` in any of their packages. This is important because requiring users to import golang-jwt directly can cause version mismatches when trying to manage dependencies.
=> Expose jwt-go MapClaims through gin-jwt.
