auth_jwt_test.go

fix #4 test Authorizator

---

auth_jwt.go
auth_jwt_test.go

fix #6 Add Test Claims During Authorization

---

.gitignore
example/server.go

[ci skip] add example. fix #8

---

.gitignore
.travis.yml

fix #9 Add code coverage.

---

auth_jwt.go
auth_jwt_test.go

fix #14 Improve check Middleware config.

---

auth_jwt_test.go

Using [gofight](https://github.com/appleboy/gofight) testing tool.

Fix #16 Using gofight

---

README.md
auth_jwt.go
auth_jwt_test.go
example/server.go

Fix #18 support user define Unauthorized method.

---

auth_jwt_test.go

Test Empty Claims

---

auth_jwt.go
auth_jwt_test.go

fix #21 typo.

---

Makefile
auth_jwt.go
auth_jwt_test.go

related issue #28 
Release v1.0.0 using `jwt-go` v2 version 
http://gopkg.in/dgrijalva/jwt-go.v2

release 1.0.0 using go-jwt v2 version.

---

README.md
auth_jwt.go
auth_jwt_test.go

Support jwt-go v3.

---

auth_jwt.go
auth_jwt_test.go

replace log.Fatal with 500 error mesagge.

---

example/server.go

fix #40 update example code.

---

.travis.yml

Support 1.7.1 testing.

---

.drone.yml
Makefile
README.md
auth_jwt.go
auth_jwt_test.go
example/server.go
glide.lock

Support fetch token from cookie, query or header 

---

README.md
auth_jwt.go
auth_jwt_test.go
example/server.go
vendor/vendor.json

fix: revert gopkg.in to github.com

---

README.md
auth_jwt.go
auth_jwt_test.go

the default value is `Bearer`
fix #57

feat: Support change default head name

---

auth_jwt.go

like flask_jwt, add a identity handler will be more flexible.

support IdentityHandler.

---

README.md
auth_jwt.go
example/server.go

feat: add TimeFunc provides the current time.

---

README.md

fix #75 update readme.

---

README.md
example/server.go

fix https://github.com/appleboy/gin-jwt/issues/83

Add ExtractClaims example.

---

auth_jwt.go
auth_jwt_test.go

HTTPStatusMessageFunc allows users to override HTTP status messages, for example in my use case I have the need to translate the status messages. To make it easer to check the error messages I also moved all errors to their own exported variables, making it easer to check against them outside the middleware.
By default HTTPStatusMessageFunc only returns the error as a string, making sure it has the same behavior as today.

Add HTTPStatusMessageFunc to allow users to override status messages

---

auth_jwt.go

Hi, I send the PR to fix the issue.

fix #82, add the code reply with login and refresh

---

auth_jwt.go

report from https://github.com/appleboy/gin-jwt/commit/b1e632599806ae9e7169c50818c30ea6031a6bb5#r26378011
Thanks @cinek260

fix(auth): update token variable.

---

auth_jwt.go
auth_jwt_test.go

fix(login): error checking for MiddlewareInit()

---

auth_jwt.go
auth_jwt_test.go

fix: change string to interface in Payload func.

---

README.md
auth_jwt.go
auth_jwt_test.go
example/server.go

change userid from string to interface{}

---

.drone.yml
Makefile
README.md
auth_jwt.go
example/server.go

see https://github.com/golangci/golangci-lint

fix: lint error from golangci-lint

---

auth_jwt.go
auth_jwt_test.go

feat: improve TokenGenerator func

---

.gitignore
auth_jwt.go
auth_jwt_test.go

fix https://github.com/appleboy/gin-jwt/pull/129

feat: save jwt token string in gin context

---

auth_jwt.go

fix https://github.com/appleboy/gin-jwt/issues/128

fix: set orig_iat as current time

---

README.md
auth_jwt.go
example/server.go

Add supports for multiple TokenLookup

---

auth_jwt.go
auth_jwt_test.go

refactor: LoginHandler method with customized function

---

auth_jwt.go
auth_jwt_test.go

fix https://github.com/appleboy/gin-jwt/issues/108

feat: Make gin-jwt return Authorization headers

---

README.md
auth_jwt_test.go
example/basic/server.go

Change example and test Bind -> ShouldBind

---

auth_jwt.go

Sometimes I need just to keep request going even if auth is failed.

Disable abort option

---

auth_jwt.go
auth_jwt_test.go

fix https://github.com/appleboy/gin-jwt/issues/153

feat: Add new func for initial jwt middleware.

---

auth_jwt.go
auth_jwt_test.go
go.mod

refactor: MapClaims interface

---

auth_jwt.go
auth_jwt_test.go

fixed https://github.com/appleboy/gin-jwt/issues/176

fix: Cannot refresh expired token, even if within MaxRefresh time

---

auth_jwt.go
auth_jwt_test.go

support parse string of token.

---

auth_jwt.go
auth_jwt_test.go

feat: support ExtractClaimsFromToken func

---

README.md

docs: update usage.

---

.drone.yml

chore: support go1.13

---

auth_jwt.go

Correct word spell in comment

---

README.md
auth_jwt.go

Add important notes in README.
See the repo: https://github.com/lmammino/jwt-cracker
fix https://github.com/appleboy/gin-jwt/issues/260

chore(jwt): change default signing algorithm

---

auth_jwt.go

Add type variable names to some closure functions in GinJWTMiddleware to clarify the meaning

---

auth_jwt.go

Hi, i want to add private key to private key(in some cases you have it)

Add Passphrase to private key 
